name: expando
description: Expando weak reference example
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.2.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  vm_service: ^15.0.0

dev_dependencies:
  lints: ^5.0.0
